export const projects = [
  {
    title: "Qualité des eaux à Lacanau",
    subtitle: "React, Node, NestJS, Postgres",
    description:
    "Application React affichant la qualité des eaux à Lacanau via un input, changeant directement l'emoji associé à la propreté de l'eau. L'application montre aussi les qualités des eaux des villes voisines grâce à des APIs qui elles mêmes prennent leur valeurs de requêtes ou d'une base de donnée postée sur AWS.",
    image: "./app_lacanau.gif",
    link: "https://github.com/CardonClement/application_qualite_des_eaux_Lacanau",
  },
  {
    title: "Situations d'Apprentissage Evaluées",
    subtitle: "Python, Java, SQL (Postgres), Bash, HTML/CSS, PHP (Laravel), JavaScript et TypeScript (Angular, React.js)",
    description:
    "Les Situations d'Aprentissage Evaluées (ou 'SAEs') sont des simulations de projets d'entreprise. Ces dernières m'ont appris de nombreuses compétences : Projet Java de grande envergure, algorithmes de tris en pyton, création/exploitation d'une base de donnée PostgreSQL, Projet Laravel <<fullstack>>, Développement d'un site web (frontend) Angular et association avec une API en Php (Laravel), Projet de site web <<fullstack>> associant React.js (frontend), Springboot (backend) et une API Flask, configuration de postes de travails et tables de routages...",
    image: "./SAE.png",
    },
];

export const skills = [
  "JavaScript",
  "TypeScript",
  "React.js",
  "AdonisJS",
  "NextJS",
  "Angular",
  "Node",
  "NestJS",
  "PHP",
  "Laravel",
  "Symfony",
  "Python",
  "Django",
  "Flask",
  "Java",
  "SpringBoot",
  "Hibernate",
  "Swing",
  "Vaadin",
  "JavaFX",
  "Kotlin (Android Studio)",
  "Bash",
  "Assembleur",
  "Langage C",
  "Langage C#",
  "Rust",
  "Axum",
  "Powershell",
  "SQL, PL/pgSQL",
  "Postgres",
  "MongoDB",
  "Docker",
  "CI via AWS (base de données), Netlify et GitLab",
  "Git, GitLab, GitHub",
  "Trello",
  "Jira",
  "Notion",
  "OBS",
  "Photoshop", 
  "Wildfly/JBoss"
];
